title: Bernardo Sobral # your name (or website title) here
logo: "/images/eu.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <div style="text-align: center">
  <a href="https://bernardosobral.github.io/pdf/bernardo_sobral.pdf">Currículo</a> |
  <a href="https://www.linkedin.com/in/bernardo-sobral-56399b66/">LinkedIn</a> |
  <a href="https://github.com/bernardosobral">Github</a>
  <br> <br>
  </div>
  
  Estou cursando graduação em Data Science; extensão em Data Science & Machine Learning e sou bacharel em Desenho Industrial.
  <br> <br>
  
  Atualmente sou autônomo / consultor em Ciência de Dados na criação de portfólio de robôs investidores do Mercado Financeiro.
  <br> <br>
  
  
theme: jekyll-theme-minimal
google_analytics: G-0T0S0F0DJK # your Google Analytics tracking ID here
