title: Bernardo Sobral # your name (or website title) here
logo: "/images/eu.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Desenvolvedor.<br>
  Interesses: Data Science, Machine Learning, AI, Python, Análise Preditiva, Mercado Financeiro.
  <br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/bernardo-sobral-56399b66/">Ver perfil LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-0T0S0F0DJK # your Google Analytics tracking ID here
